#ifndef __CMD_PC_H__
#define __CMD_PC_H__

#include "watch_config.h"
#ifdef WATCH_CHIP_TEST
#define UART_PC_PACKET_HEADER				(0x96)
#else
#define UART_PACKET_HEADER				(0xA5)
#endif


#define PC_UART_CCOMMAND_MASK_BOOTLOADER_POSITION             (8)
#define PC_UART_CCOMMAND_MASK_APPLICATION_POSITION            (9)
#define PC_UART_CCOMMAND_MASK_UPDATE_ALGORITHM_POSITION       (10)
#define PC_UART_CCOMMAND_MASK_HARDWARE_TEST_POSITION          (11)



#ifdef WATCH_CHIP_TEST
#define PC_UART_CCOMMAND_MASK_BOOTLOADER      ((1<<PC_UART_CCOMMAND_MASK_BOOTLOADER_POSITION)<<8|(UART_PC_PACKET_HEADER))
#else
#define PC_UART_CCOMMAND_MASK_BOOTLOADER      ((1<<PC_UART_CCOMMAND_MASK_BOOTLOADER_POSITION)<<8|(UART_PACKET_HEADER))
#endif

#define PC_UART_CCOMMAND_BOOTLOADER_UNSPPORT       					(0xFF<<8)

#define PC_UART_CCOMMAND_BOOTLOADER_BOOT_SETTING      					(0x01<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_PREVALIDATE     						(0x02<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_IMAGE_DATA      						(0x03<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_IMAGE_WRITE     						(0x04<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_POSTVALIDATE      					(0x05<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_RESET_N_ACTIVATE  					(0x06<<8)

#define PC_UART_RESPONSE_BOOTLOADER_BOOT_SETTING      					(0x81<<8)
#define PC_UART_RESPONSE_BOOTLOADER_PREVALIDATE     						(0x82<<8)
#define PC_UART_RESPONSE_BOOTLOADER_IMAGE_DATA      						(0x83<<8)
#define PC_UART_RESPONSE_BOOTLOADER_IMAGE_WRITE     						(0x84<<8)
#define PC_UART_RESPONSE_BOOTLOADER_POSTVALIDATE      					(0x85<<8)
#define PC_UART_RESPONSE_BOOTLOADER_RESET_N_ACTIVATE  					(0x86<<8)


#define PC_UART_CCOMMAND_BOOTLOADER_INFO_APOLLO2               (0x11<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_JUMP_BOOTLOADER            (0x12<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_JUMP_APPLICATION           (0x13<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_JUMP_UPDATE_ALGORITHM      (0x14<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_RESET                      (0x15<<8)


#define PC_UART_RESPONSE_BOOTLOADER_INFO_APOLLO2               (0x91<<8)
#define PC_UART_RESPONSE_BOOTLOADER_JUMP_BOOTLOADER            (0x92<<8)
#define PC_UART_RESPONSE_BOOTLOADER_JUMP_APPLICATION           (0x93<<8)
#define PC_UART_RESPONSE_BOOTLOADER_JUMP_UPDATE_ALGORITHM      (0x94<<8)
#define PC_UART_RESPONSE_BOOTLOADER_RESET                      (0x95<<8)





#define PC_UART_CCOMMAND_BOOTLOADER_BLE_INFO                             (0x21<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_JUMP_BOOTLOADER                  (0x22<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_JUMP_APPLICATION                 (0x23<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_RESET                            (0x24<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_BOOTSETTING                      (0x25<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_PREVALIDATE                      (0x26<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_IMAGE_DATA                       (0x27<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_IMAGE_WRITE                      (0x28<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_POSTVALIDATE                     (0x29<<8)
#define PC_UART_CCOMMAND_BOOTLOADER_BLE_RESET_N_ACTIVATE                 (0x2A<<8)


#define PC_UART_RESPONSE_BOOTLOADER_BLE_INFO                             (0xA1<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_JUMP_BOOTLOADER                  (0xA2<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_JUMP_APPLICATION                 (0xA3<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_RESET                            (0xA4<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_BOOTSETTING                      (0xA5<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_PREVALIDATE                      (0xA6<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_IMAGE_DATA                       (0xA7<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_IMAGE_WRITE                      (0xA8<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_POSTVALIDATE                     (0xA9<<8)
#define PC_UART_RESPONSE_BOOTLOADER_BLE_RESET_N_ACTIVATE                 (0xAA<<8)



#ifdef WATCH_CHIP_TEST
#define PC_UART_COMMAND_MASK_APPLICATION               ((1<<PC_UART_CCOMMAND_MASK_APPLICATION_POSITION)<<8|(UART_PC_PACKET_HEADER))
#else
#define PC_UART_COMMAND_MASK_APPLICATION               ((1<<PC_UART_CCOMMAND_MASK_APPLICATION_POSITION)<<8|(UART_PACKET_HEADER))
#endif
#define PC_UART_CCOMMAND_APPLICATION_UNSPPORT       			(0xFF<<8)

#define PC_UART_CCOMMAND_APPLICATION_FLASH_READ_RAW				(0x01<<8)
#define PC_UART_CCOMMAND_APPLICATION_FLASH_WRITE_RAW			(0x02<<8)
#define PC_UART_CCOMMAND_APPLICATION_FLASH_ERASE_RAW			(0x03<<8)
#ifdef COD
#define PC_UART_CCOMMAND_APPLICATION_MAC_READ					(0x04<<8)
#define PC_UART_CCOMMAND_APPLICATION_MAC_WRITE					(0x05<<8)
#define PC_UART_CCOMMAND_APPLICATION_FACTORY_RESET              (0x16<<8)


#define PC_UART_RESPONSE_APPLICATION_MAC_READ					(0x84<<8)
#define PC_UART_RESPONSE_APPLICATION_MAC_WRITE					(0x85<<8)
#define PC_UART_RESPONSE_APPLICATION_FACTORY_RESET              (0x96<<8)
#endif

#define PC_UART_CCOMMAND_APPLICATION_WATCH_FACE_INFO			(0x0A<<8)
#define PC_UART_CCOMMAND_APPLICATION_WATCH_FACE_INFO2			(0x0B<<8)


#define PC_UART_RESPONSE_APPLICATION_FLASH_READ_RAW				(0x81<<8)
#define PC_UART_RESPONSE_APPLICATION_FLASH_WRITE_RAW			(0x82<<8)
#define PC_UART_RESPONSE_APPLICATION_FLASH_ERASE_RAW			(0x83<<8)



#define PC_UART_RESPONSE_APPLICATION_WATCH_FACE_INFO			(0x8A<<8)
#define PC_UART_RESPONSE_APPLICATION_WATCH_FACE_INFO_2			(0x8B<<8)


#define PC_UART_CCOMMAND_APPLICATION_INFO_APOLLO2               (0x17<<8)
#define PC_UART_CCOMMAND_APPLICATION_JUMP_BOOTLOADER            (0x12<<8)
#define PC_UART_CCOMMAND_APPLICATION_JUMP_APPLICATION           (0x13<<8)
#define PC_UART_CCOMMAND_APPLICATION_JUMP_UPDATE_ALGORITHM      (0x14<<8)
#define PC_UART_CCOMMAND_APPLICATION_RESET                      (0x15<<8)


#define PC_UART_RESPONSE_APPLICATION_INFO_APOLLO2               (0x91<<8)
#define PC_UART_RESPONSE_APPLICATION_JUMP_BOOTLOADER            (0x92<<8)
#define PC_UART_RESPONSE_APPLICATION_JUMP_APPLICATION           (0x93<<8)
#define PC_UART_RESPONSE_APPLICATION_JUMP_UPDATE_ALGORITHM      (0x94<<8)
#define PC_UART_RESPONSE_APPLICATION_RESET                      (0x95<<8)




#define PC_UART_CCOMMAND_APPLICATION_BLE_INFO                             (0x21<<8)
#define PC_UART_CCOMMAND_APPLICATION_BLE_JUMP_BOOTLOADER                  (0x22<<8)
#define PC_UART_CCOMMAND_APPLICATION_BLE_JUMP_APPLICATION                 (0x23<<8)
#define PC_UART_CCOMMAND_APPLICATION_BLE_RESET                            (0x24<<8)


#define PC_UART_RESPONSE_APPLICATION_BLE_INFO                             (0xA1<<8)
#define PC_UART_RESPONSE_APPLICATION_BLE_JUMP_BOOTLOADER                  (0xA2<<8)
#define PC_UART_RESPONSE_APPLICATION_BLE_JUMP_APPLICATION                 (0xA3<<8)
#define PC_UART_RESPONSE_APPLICATION_BLE_RESET                            (0xA4<<8)




#ifdef WATCH_CHIP_TEST
#define PC_UART_COMMAND_MASK_UPDATE_ALGORITHM           ((1<<PC_UART_CCOMMAND_MASK_UPDATE_ALGORITHM_POSITION)<<8|(UART_PC_PACKET_HEADER))
#else
#define PC_UART_COMMAND_MASK_UPDATE_ALGORITHM           ((1<<PC_UART_CCOMMAND_MASK_UPDATE_ALGORITHM_POSITION)<<8|(UART_PACKET_HEADER))
#endif
#define PC_UART_CCOMMAND_UPDATE_ALGORITHM_UNSPPORT       			(0xFF<<8)

#define PC_UART_RESPONSE_UPDATE_ALGORITHM_BOOTLOADER_CRC_ERROR        (0x81<<8)
#define PC_UART_RESPONSE_UPDATE_ALGORITHM_APPLICATION_CRC_ERROR       (0x82<<8)
#define PC_UART_RESPONSE_UPDATE_ALGORITHM_BOOTLOADER_SUCCESS          (0x83<<8)
#define PC_UART_RESPONSE_UPDATE_ALGORITHM_APPLICATION_SUCCESS         (0x84<<8)




#define PC_UART_CCOMMAND_UPDATE_ALGORITHM_INFO_APOLLO2               (0x11<<8)
#define PC_UART_CCOMMAND_UPDATE_ALGORITHM_JUMP_BOOTLOADER            (0x12<<8)
#define PC_UART_CCOMMAND_UPDATE_ALGORITHM_JUMP_APPLICATION           (0x13<<8)
#define PC_UART_CCOMMAND_UPDATE_ALGORITHM_JUMP_UPDATE_ALGORITHM      (0x14<<8)
#define PC_UART_CCOMMAND_UPDATE_ALGORITHM_JUMP_RESET                 (0x15<<8)

#define PC_UART_RESPONSE_UPDATE_ALGORITHM_INFO_APOLLO2               (0x91<<8)
#define PC_UART_RESPONSE_UPDATE_ALGORITHM_JUMP_BOOTLOADER            (0x92<<8)
#define PC_UART_RESPONSE_UPDATE_ALGORITHM_JUMP_APPLICATION           (0x93<<8)
#define PC_UART_RESPONSE_UPDATE_ALGORITHM_JUMP_UPDATE_ALGORITHM      (0x94<<8)
#define PC_UART_RESPONSE_UPDATE_ALGORITHM_JUMP_RESET                 (0x95<<8)





#ifdef WATCH_CHIP_TEST
#define PC_UART_COMMAND_MASK_HARDWARE_TEST           ((1<<PC_UART_CCOMMAND_MASK_HARDWARE_TEST_POSITION)<<8|(UART_PC_PACKET_HEADER))
#else
#define PC_UART_COMMAND_MASK_HARDWARE_TEST           ((1<<PC_UART_CCOMMAND_MASK_HARDWARE_TEST_POSITION)<<8|(UART_PACKET_HEADER))
#endif
#define PC_UART_COMMAND_HARDWARE_TEST_UNSPPORT       					         (0xFF<<8)

#define PC_UART_COMMAND_HARDWARE_TEST_MODE_ENABLE                      (0x01<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MODE_DISABLE                     (0x02<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_ENABLE                (0x03<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_PRESS                 (0x04<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_DISABLE               (0x05<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_ENABLE                 (0x06<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_PRESS                  (0x07<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_DISABLE                (0x08<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_ENABLE                 (0x09<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_PRESS                  (0x0A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_DISABLE                (0x0B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_ENABLE                 (0x0C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_PRESS                  (0x0D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_DISABLE                (0x0E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_ENABLE                (0x11<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_PRESS                 (0x12<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_DISABLE      				 (0x13<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_ENABLE              				 (0x14<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_DISABLE              				 (0x15<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_ENABLE              	 (0x16<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_DISABLE              	 (0x17<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_ENABLE              			 (0x18<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_DISABLE              			 (0x19<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_ENABLE              			 (0x1A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_DISABLE              		 (0x1B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ENABLE              		 (0x1C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_SECTOR              		 (0x1D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK32              	 (0x1E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK64              	 (0x21<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ERASE              		 (0x22<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_READ              		   (0x23<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_WRITE              		 (0x24<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_DISABLE              	 (0x25<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ENABLE              		 		 (0x26<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ERASE              		     (0x27<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_READ              		       (0x28<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_WRITE              		     (0x29<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_DISABLE              	     (0x2A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_ENABLE              		 (0x2B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_READ              		   (0x2C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT1              		   (0x2D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT2              		   (0x2E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_DISABLE              	   (0x31<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_ENABLE              		     (0x32<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_READ              		       (0x33<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_DISABLE              	     (0x34<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_ENABLE              		 (0x35<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_READ              		   (0x36<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_DISABLE              	   (0x37<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_ENABLE                   		 (0x38<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_READ                   		   (0x39<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_DISABLE                  	   (0x3A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_ENABLE                   		 (0x3B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_HOT_START             (0x3C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_WARM_START            (0x3D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_COLD_START            (0x3E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_MODE              (0x41<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_BD_MODE               (0x42<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_BD_MODE           (0x43<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GGA              (0x44<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSA              (0x45<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSV              (0x46<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_RMC              (0x47<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_VTG              (0x48<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GLL              (0x49<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_ZDA              (0x4A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_READ                         (0x4B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_DISABLE                  	   (0x4C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_ENABLE                   		 (0x4D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_INFO_READ                    (0x4E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ                    (0x51<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ_STOP               (0x52<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_EXTFLASH_READ                (0x53<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_DISABLE                  	   (0x54<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_PRESSURE_ENABLE              	   (0x55<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_PRESSURE_READ              	   (0x56<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_PRESSURE_DISABLE             	   (0x57<<8)
#ifdef WATCH_CHIP_TEST
#define PC_UART_COMMAND_HARDWARE_TEST_SIXAXIS_ID_READ             	   (0x58<<8) //??id????
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_ID_READ             	   (0x59<<8) //??id????
#define PC_UART_COMMAND_HARDWARE_TEST_FLASH_ID_READ             	   (0x5A<<8) //??id????
#define PC_UART_COMMAND_HARDWARE_TEST_HEART_ID_READ             	   (0x5B<<8) //??id????
#endif

#if defined WATCH_IMU_CALIBRATION
//?????
#define PC_UART_COMMAND_HARDWARE_TEST_ACC_CAL             	           (0x70<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_ACC_CAL_PARAMETER_GET            (0x71<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_WATCH_RESET                      (0x72<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_RESET_IMU_PARAMETER              (0x73<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_CAL                         (0x74<<8)
#endif


#define PC_UART_COMMAND_HARDWARE_TEST_IMU_CALIBRATION_READ_PARAM_RESPONSE (0xF2<<8)


#define PC_UART_COMMAND_HARDWARE_TEST_MODE_ENABLE_RESPONSE             (0x81<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MODE_DISABLE_RESPONSE            (0x82<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_ENABLE_RESPONSE       (0x83<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_PRESS_RESPONSE        (0x84<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_DISABLE_RESPONSE      (0x85<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_ENABLE_RESPONSE        (0x86<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_PRESS_RESPONSE         (0x87<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_DISABLE_RESPONSE       (0x88<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_ENABLE_RESPONSE        (0x89<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_PRESS_RESPONSE         (0x8A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_DISABLE_RESPONSE       (0x8B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_ENABLE_RESPONSE        (0x8C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_PRESS_RESPONSE         (0x8D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_DISABLE_RESPONSE       (0x8E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_ENABLE_RESPONSE       (0x91<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_PRESS_RESPONSE        (0x92<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_DISABLE_RESPONSE      (0x93<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_ENABLE_RESPONSE              (0x94<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_DISABLE_RESPONSE             (0x95<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_ENABLE_RESPONSE        (0x96<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_DISABLE_RESPONSE       (0x97<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_ENABLE_RESPONSE            (0x98<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_DISABLE_RESPONSE           (0x99<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_ENABLE_RESPONSE           (0x9A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_DISABLE_RESPONSE          (0x9B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ENABLE_RESPONSE         (0x9C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_SECTOR_RESPONSE         (0x9D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK32_RESPONSE        (0x9E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK64_RESPONSE        (0xA1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ERASE_RESPONSE          (0xA2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_READ_RESPONSE           (0xA3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_WRITE_RESPONSE          (0xA4<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_DISABLE_RESPONSE        (0xA5<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ENABLE_RESPONSE             (0xA6<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ERASE_RESPONSE              (0xA7<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_READ_RESPONSE               (0xA8<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_WRITE_RESPONSE              (0xA9<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_DISABLE_RESPONSE            (0xAA<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_ENABLE_RESPONSE          (0xAB<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_READ_RESPONSE            (0xAC<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT1_RESPONSE            (0xAD<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT2_RESPONSE            (0xAE<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_DISABLE_RESPONSE         (0xB1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_ENABLE_RESPONSE             (0xB2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_READ_RESPONSE               (0xB3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_DISABLE_RESPONSE            (0xB4<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_ENABLE_RESPONSE          (0xB5<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_READ_RESPONSE            (0xB6<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_DISABLE_RESPONSE         (0xB7<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_ENABLE_RESPONSE               (0xB8<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_READ_RESPONSE                 (0xB9<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_DISABLE_RESPONSE              (0xBA<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_ENABLE_RESPONSE              (0xBB<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_HOT_START_RESPONSE    (0xBC<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_WARM_START_RESPONSE   (0xBD<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_COLD_START_RESPONSE   (0xBE<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_MODE_RESPONSE     (0xC1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_BD_MODE_RESPONSE      (0xC2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_BD_MODE_RESPONSE  (0xC3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GGA_RESPONSE     (0xC4<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSA_RESPONSE     (0xC5<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSV_RESPONSE     (0xC6<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_RMC_RESPONSE     (0xC7<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_VTG_RESPONSE     (0xC8<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GLL_RESPONSE     (0xC9<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_ZDA_RESPONSE     (0xCA<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_READ_RESPONSE                (0xCB<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_DISABLE_RESPONSE             (0xCC<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_ENABLE_RESPONSE              (0xCD<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_INFO_READ_RESPONSE           (0xCE<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ_RESPONSE           (0xD1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ_STOP_RESPONSE      (0xD2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_EXTFLASH_READ_RESPONSE       (0xD3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_DISABLE_RESPONSE             (0xD4<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_PRESSURE_ENABLE_RESPONSE     		 (0xD5<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_PRESSURE_READ_RESPONSE     		   (0xD6<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_PRESSURE_DISABLE_RESPONSE    	   (0xD7<<8)
#ifdef WATCH_CHIP_TEST
#define PC_UART_COMMAND_HARDWARE_TEST_SIXAXIS_ID_READ_RESPONSE          (0xD8<<8)//??id????, 1-??,0-??
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_ID_READ_RESPONSE          (0xD9<<8)//??id????, 1-??,0-??
#define PC_UART_COMMAND_HARDWARE_TEST_FLASH_ID_READ_RESPONSE            (0xDA<<8)//??id????, 1-??,0-??
#define PC_UART_COMMAND_HARDWARE_TEST_HEART_ID_READ_RESPONSE            (0xDB<<8)//??id????, 1-??,0-??
#endif




typedef struct __attribute__ ((packed))
{

	uint32_t command;
	uint32_t bootloader_version;
	uint32_t application_version;
	uint32_t update_version;
	uint32_t pcb_version;
	uint32_t chip_id_0;
	uint32_t chip_id_1;
	uint8_t model[5];
	uint32_t protocal_version;

	
} _info_apollo2;





#endif //__CMD_PC_H__
