#ifndef __CMD_APOLLO2_H__
#define __CMD_APOLLO2_H__

#include <stdint.h>
#if defined(LAYER_APPLICATION )
#include "watch_config.h"
#endif

#define UART_PACKET_HEADER				(0xA5)


#define PC_UART_CCOMMAND_MASK_BOOTLOADER_POSITION             (8)
#define PC_UART_CCOMMAND_MASK_APPLICATION_POSITION            (9)
#define PC_UART_CCOMMAND_MASK_UPDATE_ALGORITHM_POSITION       (10)
#define PC_UART_CCOMMAND_MASK_HARDWARE_TEST_POSITION          (11)
#define BLE_UART_CCOMMAND_MASK_APP_POSITION                    (12)





#define BLE_UART_CCOMMAND_MASK_BOOTLOADER                                  ((1<<PC_UART_CCOMMAND_MASK_BOOTLOADER_POSITION)<<8|(UART_PACKET_HEADER))

#define BLE_UART_CCOMMAND_BOOTLOADER_UNSPPORT       		            			 (0xFF<<8)





#define BLE_UART_CCOMMAND_BOOTLOADER_BLE_INFO                              (0x21<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_JUMP_BOOTLOADER                       (0x22<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_JUMP_APPLICATION                      (0x23<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_RESET                                 (0x24<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_BOOTSETTING                       (0x25<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_PREVALIDATE                       (0x26<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_IMAGE_DATA                        (0x27<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_IMAGE_WRITE                       (0x28<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_POSTVALIDATE                      (0x29<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_RESET_N_ACTIVATE                  (0x2A<<8)



#define BLE_UART_RESPONSE_BOOTLOADER_BLE_INFO                              (0xA1<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_JUMP_BOOTLOADER                       (0xA2<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_JUMP_APPLICATION                      (0xA3<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_RESET                                 (0xA4<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_BOOTSETTING                       (0xA5<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_PREVALIDATE                       (0xA6<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_IMAGE_DATA                        (0xA7<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_IMAGE_WRITE                       (0xA8<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_POSTVALIDATE                      (0xA9<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_RESET_N_ACTIVATE                  (0xAA<<8)








#define BLE_UART_CCOMMAND_MASK_APPLICATION                                 ((1<<PC_UART_CCOMMAND_MASK_APPLICATION_POSITION)<<8|(UART_PACKET_HEADER))

#define BLE_UART_CCOMMAND_APPLICATION_UNSPPORT       		            			 ((0xFF)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_APP_ERROR      		            			 ((0xFE)<<8)
/*
命令
*/
#define BLE_UART_CCOMMAND_APPLICATION_INFO_APOLLO2                        ((0x11)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_APOLLO2_JUMP_BOOTLOADER             ((0x12)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_APOLLO2_JUMP_APPLICATION            ((0x13)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_APOLLO2_JUMP_UPDATE_ALGORITHM       ((0x14)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_APOLLO2_RESET                       ((0x15)<<8)
#ifdef SOS_ADVERTISING 
#define BLE_UART_CCOMMAND_APPLICATION_SOS_GPS                             ((0x16)<<8)				
#endif	
#ifdef COD
#define BLE_UART_CCOMMAND_APPLICATION_INFO_BAT                        	  ((0x17)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_CURRENT_TIME_READ                   ((0x18)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_LOCATION_INFO                  	  ((0x19)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_PHONE_CALL_STATUS                   ((0x1A)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_PHONE_CALL_DELAY                    ((0x1B)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ON_BIND_DEVICE                      ((0x1C)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_SEND_BIND_STATUS                    ((0x1D)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ON_SPORT_CAST                    	  ((0x1E)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ON_TRAINING_CAST                    ((0x1F)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_RT_DATA_TRANS                    	  ((0x20)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_SENSOR_DATA_TRANS                   ((0x2B)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_REST_HEARTRATE                  	  ((0x2C)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_DATA_FRAME_NUM                  	  ((0x2D)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_DELETE_DATA                  	      ((0x2E)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_MAC_READ                  	      ((0x2F)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_MAC_WRITE                  	      ((0x3F)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_UPDATA_AGPS_TIME                 	  ((0x4A)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_UPDATA_BP_START                 	  ((0x4B)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_UPDATA_BP_FINISH                 	  ((0x4C)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_REAL_TIME_LOG_TRANS                 ((0x4D)<<8)
#endif

#define BLE_UART_CCOMMAND_APPLICATION_BLE_INFO                              ((0x21)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_JUMP_BOOTLOADER                       ((0x22)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_JUMP_APPLICATION                      ((0x23)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_RESET                                 ((0x24)<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_BOOTSETTING                            (0x25<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_PREVALIDATE                       			(0x26<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_IMAGE_DATA                        			(0x27<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_IMAGE_WRITE                       			(0x28<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_POSTVALIDATE                      			(0x29<<8)
#define BLE_UART_CCOMMAND_BOOTLOADER_RESET_N_ACTIVATE                  			(0x2A<<8)
#define BLE_UART_CCOMMAND_APPLICATION_BLE_CONNECT                         ((0x31)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_BLE_DISCONNECT                      ((0x32)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_BLE_BOND                            ((0x33)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_BLE_PASSKEY                         ((0x34)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_DEV_NAME_UPDATE                     ((0x35)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_CURRENT_TIME_WRITE                  ((0x36)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_WEATHER_INFO_REQUEST                ((0x37)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_PERSONAL_INFO_READ                  ((0x38)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_PERSONAL_INFO_WRITE                 ((0x39)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_SPORTS_PARAM_READ                   ((0x3A)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_SPORTS_PARAM_WRITE                  ((0x3B)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_APP_MESSAGE_IOS                     ((0x3C)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_APP_MESSAGE_ANDROID                 ((0x3D)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_WECHAT_SPORT_DATA_REQUEST           ((0x3E)<<8)

#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_ASTRO_SYNC_REQUEST             					((0x41)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_MAIN_DAY_DATA_REQUEST          					((0x42)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_ACTIVITY_ADDRESS_REQUEST       					((0x43)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_ACTIVITY_ADDRESS_BOUNDARY_REQUEST       ((0x44)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_SHARD_TRACK_ADDRESS_REQUEST             ((0x48)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_SHARD_TRACK_HEADER_WRITE                ((0x49)<<8)

#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_REQUEST_UUID                			((0x51)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_READ_ADDRESS_REQUEST        			((0x52)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_WRITE_ADDRESS_REQUEST       			((0x53)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_REQUEST_UUID         			((0x54)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_READ_ADDRESS_REQUEST      ((0x55)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_WRITE_ADDRESS_REQUEST     ((0x56)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_NOTIFY_SWITCH                    			((0x57)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_ERASE_ADDRESS_REQUEST       			((0x58)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_ERASE_ADDRESS_REQUEST     ((0x59)<<8)

#define BLE_UART_CCOMAND_APPLICATION_SENSOR_DATA_UPLOAD  ((0x5a)<<8)

#define BLE_UART_CCOMMAND_APPLICATION_SCAN_ENABLE                         ((0x61)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_SCAN_DISABLE                        ((0x62)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ACCESSORY_HEARTRATE_CONNECT         ((0x63)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ACCESSORY_HEARTRATE_DISCONNECT      ((0x64)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ACCESSORY_RUNNING_CONNECT           ((0x65)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ACCESSORY_RUNNING_DISCONNECT        ((0x66)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ACCESSORY_CYCLING_CONNECT           ((0x67)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ACCESSORY_CYCLING_DISCONNECT        ((0x68)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_ACCESSORY_DATA_UPLOAD               ((0x69)<<8)


#define BLE_UART_CCOMMAND_APPLICATION_FIND_PHONE                          ((0x71)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_GET_WATCH_CALCULATE_PARAM_WRITE     ((0x72)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_GET_WATCH_CALCULATE_PARAM_READ      ((0x73)<<8)


#define BLE_UART_CCOMMAND_APPLICATION_WATCH_FACE_INFO                      ((0x74)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_WATCH_FACE_INFO_2                    ((0x75)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_WATCH_FACE_FINISH                    ((0x76)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_WATCH_FACE_ACTIVATE                  ((0x77)<<8)



#define BLE_UART_CCOMMAND_APPLICATION_FIND_WATCH                           ((0x79)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_GET_WATCH_DEFAULT_SPORT_MODE         ((0x7A)<<8)
#define BLE_UART_CCOMMAND_APPLICATION_SEND_GPS_TEST_DATA         		   ((0x7B)<<8)



#define BLE_UART_CCOMMAND_APPLICATION_NOTIFY_MSG_ACTION_PERFORM           	((0x01)<<8)//来电通知接听或者挂断



/*
响应
*/
#define BLE_UART_RESPONSE_APPLICATION_INFO_APOLLO2                        ((0x91)<<8)
#define BLE_UART_RESPONSE_APPLICATION_APOLLO2_JUMP_BOOTLOADER             ((0x92)<<8)
#define BLE_UART_RESPONSE_APPLICATION_APOLLO2_JUMP_APPLICATION            ((0x93)<<8)
#define BLE_UART_RESPONSE_APPLICATION_APOLLO2_JUMP_UPDATE_ALGORITHM       ((0x94)<<8)
#define BLE_UART_RESPONSE_APPLICATION_APOLLO2_RESET                       ((0x95)<<8)
#ifdef COD
#define BLE_UART_RESPONSE_APPLICATION_INFO_BAT                        	  ((0x96)<<8)
#define BLE_UART_RESPONSE_APPLICATION_CURRENT_TIME_READ                   ((0x97)<<8)
#define BLE_UART_RESPONSE_APPLICATION_LOCATION_INFO              	      ((0x98)<<8)
#define BLE_UART_RESPONSE_APPLICATION_PHONE_CALL_STATUS              	  ((0x99)<<8)
#define BLE_UART_RESPONSE_APPLICATION_PHONE_CALL_DELAY              	  ((0x9A)<<8)
#define BLE_UART_RESPONSE_APPLICATION_PHONE_CALL_CTRL             	      ((0x9B)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ON_BIND_DEVICE             	      ((0x9C)<<8)
#define BLE_UART_RESPONSE_APPLICATION_SEND_BIND_STATUS              	  ((0x9D)<<8)
#define BLE_UART_RESPONSE_APPLICATION_CMD_CAST                    		  ((0x9E)<<8)
#define BLE_UART_RESPONSE_APPLICATION_RT_TODAY                    		  ((0x9F)<<8)
#define BLE_UART_RESPONSE_APPLICATION_RT_HEART                    		  ((0xA0)<<8)
#define BLE_UART_RESPONSE_APPLICATION_SPORT_CTRL                    	  ((0xAB)<<8)
#define BLE_UART_RESPONSE_APPLICATION_SENSOR_DATA_TRAINS                  ((0xAC)<<8)
#define BLE_UART_RESPONSE_APPLICATION_REST_HEARTRATE                 	  ((0xAD)<<8)
#define BLE_UART_RESPONSE_APPLICATION_DATA_FRAME_NUM                 	  ((0xAE)<<8)
#define BLE_UART_RESPONSE_APPLICATION_DELETE_DATA                 	  	  ((0xAF)<<8)
#define BLE_UART_RESPONSE_APPLICATION_MAC_READ                	  		  ((0xCA)<<8)
#define BLE_UART_RESPONSE_APPLICATION_MAC_WRITE                	  	  	  ((0xCB)<<8)
#define BLE_UART_RESPONSE_APPLICATION_UPDATA_BP_START                 	  ((0xCC)<<8)
#define BLE_UART_RESPONSE_APPLICATION_REAL_TIME_LOG_TRAINS                ((0xCD)<<8)

#endif
#ifdef WATCH_QIWEI_SPORT_DATA
#define BLE_UART_RESPONSE_APPLICATION_SPORT_DATA_UPLOAD                  ((0xCE)<<8)
#endif
#define BLE_UART_RESPONSE_APPLICATION_BLE_INFO                              ((0xA1)<<8)
#define BLE_UART_RESPONSE_APPLICATION_JUMP_BOOTLOADER                       ((0xA2)<<8)
#define BLE_UART_RESPONSE_APPLICATION_JUMP_APPLICATION                      ((0xA3)<<8)
#define BLE_UART_RESPONSE_APPLICATION_RESET                                 ((0xA4)<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_BOOTSETTING                       			(0xA5<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_PREVALIDATE                       			(0xA6<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_IMAGE_DATA                        			(0xA7<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_IMAGE_WRITE                       			(0xA8<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_POSTVALIDATE                      			(0xA9<<8)
#define BLE_UART_RESPONSE_BOOTLOADER_RESET_N_ACTIVATE                  			(0xAA<<8)
#define BLE_UART_RESPONSE_APPLICATION_BLE_CONNECT                         ((0xB1)<<8)
#define BLE_UART_RESPONSE_APPLICATION_BLE_DISCONNECT                      ((0xB2)<<8)
#define BLE_UART_RESPONSE_APPLICATION_BLE_BOND                            ((0xB3)<<8)
#define BLE_UART_RESPONSE_APPLICATION_BLE_PASSKEY                         ((0xB4)<<8)
#define BLE_UART_RESPONSE_APPLICATION_BLE_DEV_NAME_UPDATE                 ((0xB5)<<8)
#define BLE_UART_RESPONSE_APPLICATION_CURRENT_TIME_WRITE                  ((0xB6)<<8)
#define BLE_UART_RESPONSE_APPLICATION_WEATHER_INFO_REQUEST                ((0xB7)<<8)
#define BLE_UART_RESPONSE_APPLICATION_PERSONAL_INFO_READ                  ((0xB8)<<8)
#define BLE_UART_RESPONSE_APPLICATION_PERSONAL_INFO_WRITE                 ((0xB9)<<8)
#define BLE_UART_RESPONSE_APPLICATION_SPORTS_PARAM_READ                   ((0xBA)<<8)
#define BLE_UART_RESPONSE_APPLICATION_SPORTS_PARAM_WRITE                  ((0xBB)<<8)
#define BLE_UART_RESPONSE_APPLICATION_APP_MESSAGE_IOS                     ((0xBC)<<8)
#define BLE_UART_RESPONSE_APPLICATION_APP_MESSAGE_ANDROID                 ((0xBD)<<8)
#define BLE_UART_RESPONSE_APPLICATION_WECHAT_SPORT_DATA_REQUEST           ((0xBE)<<8)

#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_ASTRO_SYNC_REQUEST             					((0xC1)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_MAIN_DAY_DATA_REQUEST          					((0xC2)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_ACTIVITY_ADDRESS_REQUEST       					((0xC3)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_ACTIVITY_ADDRESS_BOUNDARY_REQUEST       ((0xC4)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_SHARD_TRACK_ADDRESS_REQUEST             ((0xC8)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_SHARD_TRACK_HEADER_WRITE                ((0xC9)<<8)


#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_REQUEST_UUID                			((0xD1)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_READ_ADDRESS_REQUEST        			((0xD2)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_WRITE_ADDRESS_REQUEST       			((0xD3)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_REQUEST_UUID         			((0xD4)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_READ_ADDRESS_REQUEST      ((0xD5)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_WRITE_ADDRESS_REQUEST     ((0xD6)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_NOTIFY_SWITCH                    			((0xD7)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_ERASE_ADDRESS_REQUEST       			((0xD8)<<8)
#define BLE_UART_RESPONSE_APPLICATION_EXTFLASH_CONFIG_TRAIN_PLAN_RESULT_ERASE_ADDRESS_REQUEST     ((0xD9)<<8)

#define BLE_UART_RESPONSE_APPLICATION_SENSOR_DATA_UPLOAD  ((0xDA)<<8)
#define BLE_UART_APPLICATION_SENSOR_DATA_UPLOAD_TRANSFER  ((0xDB)<<8)



#define BLE_UART_RESPONSE_APPLICATION_SCAN_ENABLE                         ((0xE1)<<8)
#define BLE_UART_RESPONSE_APPLICATION_SCAN_DISABLE                        ((0xE2)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ACCESSORY_HEARTRATE_CONNECT         ((0xE3)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ACCESSORY_HEARTRATE_DISCONNECT      ((0xE4)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ACCESSORY_RUNNING_CONNECT           ((0xE5)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ACCESSORY_RUNNING_DISCONNECT        ((0xE6)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ACCESSORY_CYCLING_CONNECT           ((0xE7)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ACCESSORY_CYCLING_DISCONNECT        ((0xE8)<<8)
#define BLE_UART_RESPONSE_APPLICATION_ACCESSORY_DATA_UPLOAD               ((0xE9)<<8)

#define BLE_UART_RESPONSE_APPLICATION_FIND_PHONE                          ((0xF1)<<8)
#define BLE_UART_RESPONSE_APPLICATION_GET_WATCH_CALCULATE_PARAM_WRITE     ((0xF2)<<8)
#define BLE_UART_RESPONSE_APPLICATION_GET_WATCH_CALCULATE_PARAM_READ      ((0xF3)<<8)

#define BLE_UART_RESPONSE_APPLICATION_WATCH_FACE_INFO                      ((0xF4)<<8)
#define BLE_UART_RESPONSE_APPLICATION_WATCH_FACE_INFO_2                    ((0xF5)<<8)
#define BLE_UART_RESPONSE_APPLICATION_WATCH_FACE_FINISH                    ((0xF6)<<8)
#define BLE_UART_RESPONSE_APPLICATION_WATCH_FACE_ACTIVATE                  ((0xF7)<<8)

#define BLE_UART_RESPONSE_APPLICATION_FIND_WATCH                           ((0xF9)<<8)
#define BLE_UART_RESPONSE_APPLICATION_GET_WATCH_DEFAULT_SPORT_MODE         ((0xFA)<<8)
#define BLE_UART_RESPONSE_APPLICATION_SEND_GPS_TES_DATA                    ((0xFB)<<8)


#define BLE_UART_RESPONSE_APPLICATION_NOTIFY_MSG_ACTION_PERFORM           	((0x81)<<8)





#define PC_UART_COMMAND_MASK_HARDWARE_TEST           ((1<<PC_UART_CCOMMAND_MASK_HARDWARE_TEST_POSITION)<<8|(UART_PACKET_HEADER))

#define PC_UART_COMMAND_HARDWARE_TEST_UNSPPORT       					         (0xFF<<8)

#define PC_UART_COMMAND_HARDWARE_TEST_MODE_ENABLE                      (0x01<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MODE_DISABLE                     (0x02<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_ENABLE                (0x03<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_PRESS                 (0x04<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_DISABLE               (0x05<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_ENABLE                 (0x06<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_PRESS                  (0x07<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_DISABLE                (0x08<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_ENABLE                 (0x09<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_PRESS                  (0x0A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_DISABLE                (0x0B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_ENABLE                 (0x0C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_PRESS                  (0x0D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_DISABLE                (0x0E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_ENABLE                (0x11<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_PRESS                 (0x12<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_DISABLE      				 (0x13<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_ENABLE              				 (0x14<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_DISABLE              				 (0x15<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_ENABLE              	 (0x16<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_DISABLE              	 (0x17<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_ENABLE              			 (0x18<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_DISABLE              			 (0x19<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_ENABLE              			 (0x1A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_DISABLE              		 (0x1B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ENABLE              		 (0x1C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_SECTOR              		 (0x1D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK32              	 (0x1E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK64              	 (0x21<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ERASE              		 (0x22<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_READ              		   (0x23<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_WRITE              		 (0x24<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_DISABLE              	 (0x25<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ENABLE              		 		 (0x26<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ERASE              		     (0x27<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_READ              		       (0x28<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_WRITE              		     (0x29<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_DISABLE              	     (0x2A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_ENABLE              		 (0x2B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_READ              		   (0x2C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT1              		   (0x2D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT2              		   (0x2E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_DISABLE              	   (0x31<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_ENABLE              		     (0x32<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_READ              		       (0x33<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_DISABLE              	     (0x34<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_ENABLE              		 (0x35<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_READ              		   (0x36<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_DISABLE              	   (0x37<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_ENABLE                   		 (0x38<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_READ                   		   (0x39<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_DISABLE                  	   (0x3A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_ENABLE                   		 (0x3B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_HOT_START             (0x3C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_WARM_START            (0x3D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_COLD_START            (0x3E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_MODE              (0x41<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_BD_MODE               (0x42<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_BD_MODE           (0x43<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GGA              (0x44<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSA              (0x45<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSV              (0x46<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_RMC              (0x47<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_VTG              (0x48<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GLL              (0x49<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_ZDA              (0x4A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_READ                         (0x4B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_DISABLE                  	   (0x4C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_ENABLE                   		 (0x4D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_INFO_READ                    (0x4E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ                    (0x51<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ_STOP               (0x52<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_EXTFLASH_READ                (0x53<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_DISABLE                  	   (0x54<<8)





#define PC_UART_COMMAND_HARDWARE_TEST_MODE_ENABLE_RESPONSE             (0x81<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MODE_DISABLE_RESPONSE            (0x82<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_ENABLE_RESPONSE       (0x83<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_PRESS_RESPONSE        (0x84<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_PWR_DISABLE_RESPONSE      (0x85<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_ENABLE_RESPONSE        (0x86<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_PRESS_RESPONSE         (0x87<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_BL_DISABLE_RESPONSE       (0x88<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_ENABLE_RESPONSE        (0x89<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_PRESS_RESPONSE         (0x8A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_UP_DISABLE_RESPONSE       (0x8B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_ENABLE_RESPONSE        (0x8C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_PRESS_RESPONSE         (0x8D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_OK_DISABLE_RESPONSE       (0x8E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_ENABLE_RESPONSE       (0x91<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_PRESS_RESPONSE        (0x92<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUTTON_DWN_DISABLE_RESPONSE      (0x93<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_ENABLE_RESPONSE              (0x94<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_LCD_DISABLE_RESPONSE             (0x95<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_ENABLE_RESPONSE        (0x96<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BACKLIGHT_DISABLE_RESPONSE       (0x97<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_ENABLE_RESPONSE            (0x98<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_MOTOR_DISABLE_RESPONSE           (0x99<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_ENABLE_RESPONSE           (0x9A<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BUZZER_DISABLE_RESPONSE          (0x9B<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ENABLE_RESPONSE         (0x9C<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_SECTOR_RESPONSE         (0x9D<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK32_RESPONSE        (0x9E<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_BLOCK64_RESPONSE        (0xA1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_ERASE_RESPONSE          (0xA2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_READ_RESPONSE           (0xA3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_WRITE_RESPONSE          (0xA4<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_EXTFLASH_DISABLE_RESPONSE        (0xA5<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ENABLE_RESPONSE             (0xA6<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_ERASE_RESPONSE              (0xA7<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_READ_RESPONSE               (0xA8<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_WRITE_RESPONSE              (0xA9<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_FONT_DISABLE_RESPONSE            (0xAA<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_ENABLE_RESPONSE          (0xAB<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_READ_RESPONSE            (0xAC<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT1_RESPONSE            (0xAD<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_INT2_RESPONSE            (0xAE<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GSENSOR_DISABLE_RESPONSE         (0xB1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_ENABLE_RESPONSE             (0xB2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_READ_RESPONSE               (0xB3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GYRO_DISABLE_RESPONSE            (0xB4<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_ENABLE_RESPONSE          (0xB5<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_READ_RESPONSE            (0xB6<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_COMPASS_DISABLE_RESPONSE         (0xB7<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_ENABLE_RESPONSE               (0xB8<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_READ_RESPONSE                 (0xB9<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_HR_DISABLE_RESPONSE              (0xBA<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_ENABLE_RESPONSE              (0xBB<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_HOT_START_RESPONSE    (0xBC<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_WARM_START_RESPONSE   (0xBD<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_COLD_START_RESPONSE   (0xBE<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_MODE_RESPONSE     (0xC1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_BD_MODE_RESPONSE      (0xC2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_GPS_BD_MODE_RESPONSE  (0xC3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GGA_RESPONSE     (0xC4<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSA_RESPONSE     (0xC5<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GSV_RESPONSE     (0xC6<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_RMC_RESPONSE     (0xC7<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_VTG_RESPONSE     (0xC8<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_GLL_RESPONSE     (0xC9<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_CONFIG_NMEA_ZDA_RESPONSE     (0xCA<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_READ_RESPONSE                (0xCB<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_GPS_DISABLE_RESPONSE             (0xCC<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_ENABLE_RESPONSE              (0xCD<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_INFO_READ_RESPONSE           (0xCE<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ_RESPONSE           (0xD1<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_RSSI_READ_STOP_RESPONSE      (0xD2<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_EXTFLASH_READ_RESPONSE       (0xD3<<8)
#define PC_UART_COMMAND_HARDWARE_TEST_BLE_DISABLE_RESPONSE             (0xD4<<8)




#define BLE_UART_CCOMMAND_MASK_APP                   ((1<<BLE_UART_CCOMMAND_MASK_APP_POSITION)<<8|(UART_PACKET_HEADER))


#define BLE_UART_CCOMMAND_APP_BLE_DFU_START                          ((0x01)<<8)
#define BLE_UART_CCOMMAND_APP_BLE_DFU_FINISH                         ((0x02)<<8)
#define BLE_UART_CCOMMAND_APP_BLE_DFU_APOLLO_BOOTSETTING             ((0x03)<<8)
#define BLE_UART_CCOMMAND_APP_BLE_DFU_APOLLO_PREVALIDATE             ((0x04)<<8)
#define BLE_UART_CCOMMAND_APP_BLE_DFU_APOLLO_POSTVALIDATE            ((0x05)<<8)
#define BLE_UART_CCOMMAND_APP_BLE_DFU_APOLLO_RESET_N_ACTIVATE        ((0x06)<<8)

#define BLE_UART_RESPONSE_APP_BLE_DFU_START                          ((0x81)<<8)
#define BLE_UART_RESPONSE_APP_BLE_DFU_FINISH                         ((0x82)<<8)
#define BLE_UART_RESPONSE_APP_BLE_DFU_APOLLO_BOOTSETTING             ((0x83)<<8)
#define BLE_UART_RESPONSE_APP_BLE_DFU_APOLLO_PREVALIDATE             ((0x84)<<8)
#define BLE_UART_RESPONSE_APP_BLE_DFU_APOLLO_POSTVALIDATE            ((0x85)<<8)
#define BLE_UART_RESPONSE_APP_BLE_DFU_APOLLO_RESET_N_ACTIVATE        ((0x86)<<8)





typedef struct {

	uint32_t command;
	uint32_t bootloader_version;
	uint32_t application_version;
	uint32_t update_version;
	uint32_t pcb_version;
	uint32_t chip_id_0;
	uint32_t chip_id_1;
} _info_apollo2;


#endif //__CMD_APOLLO2_H__
