#ifndef __CMD_APOLLO_SRV_H__
#define __CMD_APOLLO_SRV_H__



/*
* 命令
*/

#define CMD_APOLLO_SRV_FLASH_READ_RAW          					               				 0x01
#define CMD_APOLLO_SRV_FLASH_WRITE_RAW          	        				     				 0x02
#define CMD_APOLLO_SRV_FLASH_ERASE_RAW          	        				     				 0x03
#define CMD_APOLLO_SRV_FLASH_CONFIG_ASTRO_SYNC_RRQUEST      	         				 0x04
#define CMD_APOLLO_SRV_FLASH_CONFIG_MAIN_DAY_DATA_RRQUEST      	       				 0x05
#define CMD_APOLLO_SRV_FLASH_CONFIG_ACTIVITY_ADDRESS_RRQUEST      	   				 0x06
#define CMD_APOLLO_SRV_FLASH_CONFIG_ACTIVITY_ADDRESS_BOUNDARY_RRQUEST      	   0x07
#define CMD_APOLLO_SRV_FLASH_CONFIG_SHARED_TRACK_ADDRESS_REQUEST      	       0x0B
#define CMD_APOLLO_SRV_FLASH_CONFIG_SHARED_TRACK_HEADER_WRITE      	           0x0C

#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_REQUEST_UUID      	             0x0D
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_READ_ADDRESS_REQUEST      	     0x0E
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_WRITE_ADDRESS_REQUEST      	   0x11
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_ERASE_ADDRESS_REQUEST      	   0x16
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_REQUEST_UUID      	     0x12
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_READ_ADDRESS_REQUEST     0x13
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_WRITE_ADDRESS_REQUEST    0x14
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_NOTIFY_SWITCH      	           0x15
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_ERASE_ADDRESS_REQUEST    0x17



#define CMD_APOLLO_SRV_FLASH_DFU_START                                         0x21
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_BOOTSETTING                               0x22
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_PREVALIDATE                               0x23
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_POSTVALIDATE                              0x24
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_RESET_N_ACTIVATE                          0x25
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_FINISH                                0x26
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_BOOTSETTING                    0x27
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_PREVALIDATE                    0x28
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_POSTVALIDATE                   0x29
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_RESET_N_ACTIVATE               0x2A

#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_INFO                           0x2B//当前表盘，1到4表盘信息
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_INFO_2                         0x2C//5到10表盘信息
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_FINISH                         0x2D
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_ACTIVATE                       0x2E
/*
* 响应
*/



#define CMD_APOLLO_SRV_FLASH_READ_RAW_RESPONSE                         									0x81
#define CMD_APOLLO_SRV_FLASH_WRITE_RAW_RESPONSE                        									0x82
#define CMD_APOLLO_SRV_FLASH_ERASE_RAW_RESPONSE                        									0x83
#define CMD_APOLLO_SRV_FLASH_CONFIG_RRQUEST_ASTRO_SYNC_RESPONSE        									0x84
#define CMD_APOLLO_SRV_FLASH_CONFIG_MAIN_DAY_DATA_RRQUEST_RESPONSE     									0x85
#define CMD_APOLLO_SRV_FLASH_CONFIG_ACTIVITY_ADDRESS_RRQUEST_RESPONSE  									0x86
#define CMD_APOLLO_SRV_FLASH_CONFIG_ACTIVITY_ADDRESS_BOUNDARY_RRQUEST_RESPONSE  				0x87
#define CMD_APOLLO_SRV_FLASH_CONFIG_SHARED_TRACK_ADDRESS_REQUEST_RESPONSE      	        0x8B
#define CMD_APOLLO_SRV_FLASH_CONFIG_SHARED_TRACK_HEADER_WRITE_RESPONSE      	          0x8C


#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_REQUEST_UUID_RESPONSE      	             0x8D
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_READ_ADDRESS_REQUEST_RESPONSE      	     0x8E
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_WRITE_ADDRESS_REQUEST_RESPONSE      	     0x91
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_ERASE_ADDRESS_REQUEST_RESPONSE        	   0x96
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_REQUEST_UUID_RESPONSE      	       0x92
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_READ_ADDRESS_REQUEST_RESPONSE      0x93
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_WRITE_ADDRESS_REQUEST_RESPONSE     0x94
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_NOTIFY_SWITCH_RESPONSE       	           0x95
#define CMD_APOLLO_SRV_FLASH_CONFIG_TRAIN_PLAN_RESULT_ERASE_ADDRESS_REQUEST_RESPONSE     0x97


#define CMD_APOLLO_SRV_FLASH_DFU_START_RESPONSE                                          0xA1
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_BOOTSETTING_RESPONSE                                0xA2
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_PREVALIDATE_RESPONSE                                0xA3
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_POSTVALIDATE_RESPONSE                               0xA4
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_RESET_N_ACTIVATE_RESPONSE                           0xA5
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_FINISH_RESPONSE                                 0xA6
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_BOOTSETTING_RESPONSE                     0xA7
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_PREVALIDATE_RESPONSE                     0xA8
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_POSTVALIDATE_RESPONSE                    0xA9
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_DFU_APOLLO_RESET_N_ACTIVATE_RESPONSE                0xAA

#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_INFO_RESPONSE                            0xAB
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_INFO_2_RESPONSE                          0xAC
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_FINISH_RESPONSE                          0xAD
#define CMD_APOLLO_SRV_FLASH_DFU_BLE_WATCH_FACE_ACTIVATE_RESPONSE                        0xAE


//sensor数据特征
//命令
#define APOLLO_SENSOR_DATA_UPLOAD_COMMAND 0x01

//响应
#define APOLLO_SENSOR_DATA_UPLOAD_RESPONSE 0x81

#endif //__CMD_APOLLO_SRV_H__
