#ifndef _TASK_DISPLAY_H__
#define _TASK_DISPLAY_H__

#include <stdint.h>

#define MSG_DEFAULT						0	//do nothing
#define MSG_DISPLAY_SCREEN				1	//œ‘ æΩÁ√Ê


typedef struct{
	uint32_t cmd;
	uint32_t value;
}DISPLAY_MSG;


typedef enum
{
	SCREEN_STATE_EXCEPTION_TYPE_NONE = 0,  	
  SCREEN_STATE_EXCEPTION_TYPE_APPLICATION_START_ADDRESS_ERROR,
	SCREEN_STATE_EXCEPTION_TYPE_APPLICATION_CRC_ERROR,
	SCREEN_STATE_EXCEPTION_TYPE_UPDATE_ALGORITHM_START_ADDRESS_ERROR,
	SCREEN_STATE_EXCEPTION_TYPE_UPDATE_ALGORITHM_CRC_ERROR,
	SCREEN_STATE_EXCEPTION_TYPE_BOOTSETTING_CRC_ERROR,
	
}ScreenState_exception;

typedef enum
{
	DISPLAY_SCREEN_BOOTLOADER = 1,  	
	DISPLAY_SCREEN_POST_WATCH_INFO,  
	DISPLAY_SCREEN_BACK_DOOR, 
	
	DISPLAY_SCREEN_EXCEPTION = 200,  
	
	
}ScreenState_t;


void task_display_init(void);


#endif
